### ISSUE TITLE
Tarefa04

### ISSUE THREAD

**Issue by pietro-lopes** [ffatique/lift-learning-aula04#1]
Opa, beleza?
A tarefa 04 o professor solicitou o seguinte:
`Faça o deploy de um contrato de venda de de uma das tokens criadas acima a partir de um depósito em MATIC. Cole o endereço do contrato abaixo.`

Então teriamos que usar o endereço de um dos tokens da tarefa 01, 02 ou 03 como construtor do SellerTarefa04 em vez de importar um token novo vindo de Tarefa04, certo?

Abraço!

**Comment by ffatique** [comment]
Opa Pietro tudo bem? Isso mesmo, para a entrega do exercício você está correto.

Eu fiz desta forma criando mais um Token para poder explicar melhor pro pessoal nas aulas que fizemos no sábado e no domingo o que estava acontecendo ali com outro exemplo.
Qualquer coisa pode me enviar ai, Abraços
